# rules.py

latin_exclusions = {
    "univision", "unuvision", "univishion", "voo", "skymedia",
    "mobinet", "unitel", "computer", "windows xp", "uni", "mongolia", "back"
}

normalization_dict = {
    "avahgui": "avahgüi", 
    "solison": "soljson", "soljson": "soljson",
    "bn": "baina", "bna": "baina", "bnn": "baina",
    "bsn": "baisan", "bsan":"baisan", 
    "bnle": "baina lee", "bnlee": "baina lee",
    "baihi": "baih yum", "bhiin": "baih yum",
    "bhad": "baihad", "bhd": "baihad", 
    "bgaa": "baigaa", "bga": "baigaa",
    "bgamu": "baigaa ym uu",
    "bj": "baij",
    "bolchij": "bolchhoj",
    "buur": "büür", "bvvr": "büür",
    "unegui": "ünegüi", 
    "blhgui": "bolohgüi",
    "shiljuuleed": "shiljüüleed",
    "vzj": "üzej", "uzej": "üzej", "vzej": "üzej", "uzeegui": "üzeegüi", "vzeegui": "üzeegüi", "vzeegvi": "üzeegüi",
    "tgheer": "tegeheer",
    "zugeer": "zügeer",
    "gd": "geed", 
    "bga": "baigaa",
    "bdin": "baidag yum",
    "bdg": "baidag", "bdag": "baidag",
    "bnu": "baina uu",
    "zugeer": "zugeer", "zgr": "zugeer", "zger": "zugeer",
    "mngl": "mongol",
    "ymr": "yamar",
    "ymar": "yamar",
    "yu": "yuu", "yuu": "yuu",
    "xar": "khar", "xap": "khar", "har": "khar",
    "hun": "xun",
    "hrn": "harin", 
    "huts": "xuts",
    "hotiin": "xotiin",
    "hureerei": "hureerei",
    "hicheel": "hicheel",
    "xun": "xun",
    "tuhuurumj": "töhöörömj",
    "buren": "büren",
    "zuv": "zöv",
    "hereg": "khereg",
    "deer": "deer",
    "mungu": "möngö", "mongo": "möngö", "munguu": "möngöö", "mongoo": "möngöö",
    "shuu": "shüü", "shvv": "shüü",
    "hymd": "hyamd",
    "hynalt": "hyanalt",
    "ym": "yum", "yum": "юм",
    "tuv": "töv", "tuw": "töv",
    "tm": "tiim", 
    "yuch": "yuu ch", 
    "vzegui": "üzeegüi", 
    "sayhan": "sayaahan",
    "bayrlalaa": "bayarlalaa", "bayrlaa": "bayarlalaa",
    "ayga": "ayaga", 
    "bayr": "bayar",
    "sayhan": "sayahan",
    "tvreeselj": "türeeselj", "tureeselj": "türeeselj",
    "away": "avya", "avay": "avya", "avya": "avya", "awya": "avya", 
}

latin_to_cyrillic = {
    "ui": "уй", "vi": "үй", "üi": "үй", "ai": "ай", "ii": "ий", "kh": "х", "lj": "ль",
    "ch": "ч", "sh": "ш", "ts": "ц", "ya": "я", "yo": "ё", "yu": "ю", "ee": "ээ",
    "ö": "ө", "ü": "ү",
    "a": "а", "b": "б", "c": "ц", "d": "д", "e": "е", "f": "ф", "g": "г",
    "h": "х", "i": "и", "j": "ж", "k": "к", "l": "л", "m": "м", "n": "н",
    "o": "о", "p": "п", "q": "к", "r": "р", "s": "с", "t": "т", "u": "у",
    "v": "в", "w": "в", "x": "х", "y": "й", "z": "з"
}

digraphs = ["kh", "üi", "vi", "ui", "ai", "ii", "ch", "sh", "ts", "ya", "yo", "yu", "ee"]
